### ISSUE TITLE
 error received empty FormDigestValue

### ISSUE THREAD

**Issue by cis-nothize** [koltyakov/gosip#10]
In a long running server process, after idling for about 20 hours, the request resulted in " error received empty FormDigestValue".

How should I troubleshoot this error?

Is it a known issue?

**Comment by koltyakov** [comment]
Hi @cis-nothize,

Is not an issue which I was aware of.
What are the auth strategy and SharePoint version?

**Comment by cis-nothize** [comment]
Hi @koltyakov ,

The auth strategy is saml, and it is SharePoint online, pointing to the https://[masked].sharepoint.com/ URL.

**Comment by koltyakov** [comment]
Found a possible place with digest cache issue. Pushed an update.
Not completely sure if this is a remedy. Started a long-running test, will see.

**Comment by cis-nothize** [comment]
Thanks, I will try using the latest version.

On the other hand, I've submitted #11 to reflect the source code I'm using.

**Comment by cis-nothize** [comment]
There is no 500 error for requests being made across 14.5 hours. (20 hours was misstated before, it was 14.5 hours as calculated now)

Looks like the issue has been fixed! Thank @koltyakov! How about your test?

**Comment by koltyakov** [comment]
Cool! My tests (I looped some requests with a pattern executed each 1-5 minute) have been running for around a whole last week. The test schema is a simple web server proxying some API endpoints to SPO and a client sending requests with a delay in a cycle. No errors with a digest and a couple of errors which happen due to network issues. Looks good for me.
Once again thanks for finding out the bug and assistance! Closing the issue now.
